// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfvkoadphgtuzdsbusad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdmtvYWRwaGd0dXpkc2J1c2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Njg5OTMsImV4cCI6MjA2NTQ0NDk5M30.S4b76W8FZTMwGPPJJ8kNZKZ7rE3qV9nj2pWyeD_eaAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);